// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTi77Du0dhsomUTPtz_4ALila2sC4iW0Y',
    appId: '1:432820843570:web:7afb1de620f9c08d7cb82b',
    messagingSenderId: '432820843570',
    projectId: 'fir-ai-ensconse-test',
    authDomain: 'fir-ai-ensconse-test.firebaseapp.com',
    storageBucket: 'fir-ai-ensconse-test.firebasestorage.app',
    measurementId: 'G-5YLZZLQWE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADXeuDF3uLaycDv_AVg-TjEllAAcLFYlA',
    appId: '1:432820843570:android:ca2bad62a84df4d77cb82b',
    messagingSenderId: '432820843570',
    projectId: 'fir-ai-ensconse-test',
    storageBucket: 'fir-ai-ensconse-test.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvlJnbtXM3-sRPEbfrQYjNzM13XetiFc',
    appId: '1:432820843570:ios:e5805a1f069558f07cb82b',
    messagingSenderId: '432820843570',
    projectId: 'fir-ai-ensconse-test',
    storageBucket: 'fir-ai-ensconse-test.firebasestorage.app',
    iosBundleId: 'com.example.myThesisProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkvlJnbtXM3-sRPEbfrQYjNzM13XetiFc',
    appId: '1:432820843570:ios:e5805a1f069558f07cb82b',
    messagingSenderId: '432820843570',
    projectId: 'fir-ai-ensconse-test',
    storageBucket: 'fir-ai-ensconse-test.firebasestorage.app',
    iosBundleId: 'com.example.myThesisProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTi77Du0dhsomUTPtz_4ALila2sC4iW0Y',
    appId: '1:432820843570:web:de1531b160c878167cb82b',
    messagingSenderId: '432820843570',
    projectId: 'fir-ai-ensconse-test',
    authDomain: 'fir-ai-ensconse-test.firebaseapp.com',
    storageBucket: 'fir-ai-ensconse-test.firebasestorage.app',
    measurementId: 'G-0GET0MELHW',
  );
}
