// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'data/models/memory_item.dart';
import 'data/models/todo_task.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5641021281272264174),
    name: 'MemoryItem',
    lastPropertyId: const obx_int.IdUid(3, 5782990194078271420),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6994047580540561463),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9161832322320051394),
        name: 'memoryNum',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5782990194078271420),
        name: 'todoTaskId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 3075244279789264285),
        relationField: 'todoTask',
        relationTarget: 'TodoTask',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7082088160563669728),
    name: 'TodoTask',
    lastPropertyId: const obx_int.IdUid(12, 4242132119087631110),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8664802120879950657),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6109641334446968284),
        name: 'image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3158815864398780723),
        name: 'taskTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5317474854459270699),
        name: 'taskDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7617005923575784707),
        name: 'taskCreated',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2935928167812411647),
        name: 'taskCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3926864191900518535),
        name: 'taskNote',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 683568028229824387),
        name: 'taskDeadline',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5880904946138499885),
        name: 'ocrText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4254738970403588372),
        name: 'fileSizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 9152858038456054293),
        name: 'documentDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4242132119087631110),
        name: 'textEmbedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(3, 2920578436187358986),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'memoryItem',
        srcEntity: 'MemoryItem',
        srcField: 'todoTask',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 7082088160563669728),
    lastIndexId: const obx_int.IdUid(3, 2920578436187358986),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [733585617409178034],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5699723661572846430,
      3344861584151050767,
      8543775698328051053,
      2242668135846532794,
      8499410760694797408,
      6352211810431020316,
      7404400906733572876,
      1282978839355512294,
      4634253288640487833,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MemoryItem: obx_int.EntityDefinition<MemoryItem>(
      model: _entities[0],
      toOneRelations: (MemoryItem object) => [object.todoTask],
      toManyRelations: (MemoryItem object) => {},
      getId: (MemoryItem object) => object.id,
      setId: (MemoryItem object, int id) {
        object.id = id;
      },
      objectToFB: (MemoryItem object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.memoryNum);
        fbb.addInt64(2, object.todoTask.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = MemoryItem()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..memoryNum = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            6,
            false,
          );
        object.todoTask.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.todoTask.attach(store);
        return object;
      },
    ),
    TodoTask: obx_int.EntityDefinition<TodoTask>(
      model: _entities[1],
      toOneRelations: (TodoTask object) => [],
      toManyRelations: (TodoTask object) => {
        obx_int.RelInfo<MemoryItem>.toOneBacklink(
          3,
          object.id,
          (MemoryItem srcObject) => srcObject.todoTask,
        ): object.memoryItem,
      },
      getId: (TodoTask object) => object.id,
      setId: (TodoTask object, int id) {
        object.id = id;
      },
      objectToFB: (TodoTask object, fb.Builder fbb) {
        final imageOffset = fbb.writeString(object.image);
        final taskTitleOffset = fbb.writeString(object.taskTitle);
        final taskDescriptionOffset = fbb.writeString(object.taskDescription);
        final taskCreatedOffset = fbb.writeString(object.taskCreated);
        final taskNoteOffset = fbb.writeString(object.taskNote);
        final taskDeadlineOffset = fbb.writeString(object.taskDeadline);
        final ocrTextOffset = object.ocrText == null
            ? null
            : fbb.writeString(object.ocrText!);
        final documentDateOffset = object.documentDate == null
            ? null
            : fbb.writeString(object.documentDate!);
        final textEmbeddingOffset = object.textEmbedding == null
            ? null
            : fbb.writeListFloat32(object.textEmbedding!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, imageOffset);
        fbb.addOffset(2, taskTitleOffset);
        fbb.addOffset(3, taskDescriptionOffset);
        fbb.addOffset(4, taskCreatedOffset);
        fbb.addBool(5, object.taskCompleted);
        fbb.addOffset(6, taskNoteOffset);
        fbb.addOffset(7, taskDeadlineOffset);
        fbb.addOffset(8, ocrTextOffset);
        fbb.addInt64(9, object.fileSizeBytes);
        fbb.addOffset(10, documentDateOffset);
        fbb.addOffset(11, textEmbeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final imageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final taskTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final taskDescriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final taskCreatedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final taskCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final taskNoteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final taskDeadlineParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final fileSizeBytesParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final ocrTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final documentDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final object =
            TodoTask(
                id: idParam,
                image: imageParam,
                taskTitle: taskTitleParam,
                taskDescription: taskDescriptionParam,
                taskCreated: taskCreatedParam,
                taskCompleted: taskCompletedParam,
                taskNote: taskNoteParam,
                taskDeadline: taskDeadlineParam,
                fileSizeBytes: fileSizeBytesParam,
                ocrText: ocrTextParam,
                documentDate: documentDateParam,
              )
              ..textEmbedding = const fb.ListReader<double>(
                fb.Float32Reader(),
                lazy: false,
              ).vTableGetNullable(buffer, rootOffset, 26);
        obx_int.InternalToManyAccess.setRelInfo<TodoTask>(
          object.memoryItem,
          store,
          obx_int.RelInfo<MemoryItem>.toOneBacklink(
            3,
            object.id,
            (MemoryItem srcObject) => srcObject.todoTask,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MemoryItem] entity fields to define ObjectBox queries.
class MemoryItem_ {
  /// See [MemoryItem.id].
  static final id = obx.QueryIntegerProperty<MemoryItem>(
    _entities[0].properties[0],
  );

  /// See [MemoryItem.memoryNum].
  static final memoryNum = obx.QueryBooleanProperty<MemoryItem>(
    _entities[0].properties[1],
  );

  /// See [MemoryItem.todoTask].
  static final todoTask = obx.QueryRelationToOne<MemoryItem, TodoTask>(
    _entities[0].properties[2],
  );
}

/// [TodoTask] entity fields to define ObjectBox queries.
class TodoTask_ {
  /// See [TodoTask.id].
  static final id = obx.QueryIntegerProperty<TodoTask>(
    _entities[1].properties[0],
  );

  /// See [TodoTask.image].
  static final image = obx.QueryStringProperty<TodoTask>(
    _entities[1].properties[1],
  );

  /// See [TodoTask.taskTitle].
  static final taskTitle = obx.QueryStringProperty<TodoTask>(
    _entities[1].properties[2],
  );

  /// See [TodoTask.taskDescription].
  static final taskDescription = obx.QueryStringProperty<TodoTask>(
    _entities[1].properties[3],
  );

  /// See [TodoTask.taskCreated].
  static final taskCreated = obx.QueryStringProperty<TodoTask>(
    _entities[1].properties[4],
  );

  /// See [TodoTask.taskCompleted].
  static final taskCompleted = obx.QueryBooleanProperty<TodoTask>(
    _entities[1].properties[5],
  );

  /// See [TodoTask.taskNote].
  static final taskNote = obx.QueryStringProperty<TodoTask>(
    _entities[1].properties[6],
  );

  /// See [TodoTask.taskDeadline].
  static final taskDeadline = obx.QueryStringProperty<TodoTask>(
    _entities[1].properties[7],
  );

  /// See [TodoTask.ocrText].
  static final ocrText = obx.QueryStringProperty<TodoTask>(
    _entities[1].properties[8],
  );

  /// See [TodoTask.fileSizeBytes].
  static final fileSizeBytes = obx.QueryIntegerProperty<TodoTask>(
    _entities[1].properties[9],
  );

  /// See [TodoTask.documentDate].
  static final documentDate = obx.QueryStringProperty<TodoTask>(
    _entities[1].properties[10],
  );

  /// See [TodoTask.textEmbedding].
  static final textEmbedding = obx.QueryHnswProperty<TodoTask>(
    _entities[1].properties[11],
  );

  /// see [TodoTask.memoryItem]
  static final memoryItem = obx.QueryBacklinkToMany<MemoryItem, TodoTask>(
    MemoryItem_.todoTask,
  );
}
